version: "3.9"
services:

  db:
    container_name: hotel-booking-db
    image: postgres:latest
    env_file:
      - .env.prod
    volumes:
      - hotel-booking-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    ports:
      - "5435:5432"
    networks:
      - hotel-booking

  redis:
    container_name: hotel-booking-cache
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6378:6379"
    networks:
      - hotel-booking

  service:
    container_name: hotel-booking-service
    image: hotel-booking-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    networks:
      - hotel-booking

volumes:
  hotel-booking-db:

networks:
  hotel-booking:
