target-version = "py311"
line-length = 120

select = [
    "A",
    "B",
    "E",
    "F",
    "ISC",
    "UP",
    "RUF",
    "RET",
    "ANN",
    "I",
    "N",
    "ASYNC",
    "S",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "ARG",
    "PTH",
    "TD",
    "FIX",
    "ERA",
    "PGH",
    "FLY",
    "PERF"

]

ignore = [
    "RUF001", # Кириллические символы в string
    "RUF002", # Кириллические символы в dockstring
    "RUF003", # Кириллические символы в комментарии
    "A003", # Использование ключевых слов, которые перекрывают встроенные функции Python
    "ISC002", # Неявно объединенные строковые литералы в нескольких строках
    "ANN101",
    "ANN102",
    "PYI041"

]

fixable = ["ALL"]
unfixable = []

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations"
]
